# Example Github Workflow file to run Terraform Check action
name: Terraform Checks

on: [push]

jobs:
  terraform-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run Terraform Action from oak-terraform-actions
        uses: oaknational/oak-terraform-actions/actions/terraform-checks@9869989473667c940f47f17639bdbf1bcd118243 # v1.12.0
