# Example Github Workflow file to run Terraform Check action
name: Terraform Checks

on: [push]

jobs:
  terraform-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run Terraform Action from oak-terraform-actions
        uses: oaknational/oak-terraform-actions/actions/terraform-checks@208b99c3e0c742356de5ba33388a0ab89d14e9c7 # v1.11.0
